// generated by unplugin-vue-components
// We suggest you to commit this file into source control
// Read more: https://github.com/vuejs/core/pull/3399
import '@vue/runtime-core'

export {}

declare module '@vue/runtime-core' {
  export interface GlobalComponents {
    AAlert: typeof import('@arco-design/web-vue')['Alert']
    AAvatar: typeof import('@arco-design/web-vue')['Avatar']
    AButton: typeof import('@arco-design/web-vue')['Button']
    ACard: typeof import('@arco-design/web-vue')['Card']
    ACardMeta: typeof import('@arco-design/web-vue')['CardMeta']
    ACheckbox: typeof import('@arco-design/web-vue')['Checkbox']
    ACol: typeof import('@arco-design/web-vue')['Col']
    ADescriptions: typeof import('@arco-design/web-vue')['Descriptions']
    ADoption: typeof import('@arco-design/web-vue')['Doption']
    ADrawer: typeof import('@arco-design/web-vue')['Drawer']
    ADropdown: typeof import('@arco-design/web-vue')['Dropdown']
    AForm: typeof import('@arco-design/web-vue')['Form']
    AFormItem: typeof import('@arco-design/web-vue')['FormItem']
    AInput: typeof import('@arco-design/web-vue')['Input']
    AInputPassword: typeof import('@arco-design/web-vue')['InputPassword']
    ALayout: typeof import('@arco-design/web-vue')['Layout']
    ALayoutContent: typeof import('@arco-design/web-vue')['LayoutContent']
    ALayoutFooter: typeof import('@arco-design/web-vue')['LayoutFooter']
    ALayoutHeader: typeof import('@arco-design/web-vue')['LayoutHeader']
    ALayoutSider: typeof import('@arco-design/web-vue')['LayoutSider']
    ALink: typeof import('@arco-design/web-vue')['Link']
    AList: typeof import('@arco-design/web-vue')['List']
    AListItem: typeof import('@arco-design/web-vue')['ListItem']
    AMenu: typeof import('@arco-design/web-vue')['Menu']
    AMenuItem: typeof import('@arco-design/web-vue')['MenuItem']
    AModal: typeof import('@arco-design/web-vue')['Modal']
    AResult: typeof import('@arco-design/web-vue')['Result']
    ARow: typeof import('@arco-design/web-vue')['Row']
    ASkeleton: typeof import('@arco-design/web-vue')['Skeleton']
    ASkeletonLine: typeof import('@arco-design/web-vue')['SkeletonLine']
    ASkeletonShape: typeof import('@arco-design/web-vue')['SkeletonShape']
    ASpace: typeof import('@arco-design/web-vue')['Space']
    ASubMenu: typeof import('@arco-design/web-vue')['SubMenu']
    ATable: typeof import('@arco-design/web-vue')['Table']
    ATableColumn: typeof import('@arco-design/web-vue')['TableColumn']
    ATag: typeof import('@arco-design/web-vue')['Tag']
    ATypography: typeof import('@arco-design/web-vue')['Typography']
    ATypographyParagraph: typeof import('@arco-design/web-vue')['TypographyParagraph']
    ATypographyText: typeof import('@arco-design/web-vue')['TypographyText']
    ATypographyTitle: typeof import('@arco-design/web-vue')['TypographyTitle']
    Footer: typeof import('./components/Footer.vue')['default']
    Header: typeof import('./components/Header.vue')['default']
    PopMenu: typeof import('./components/PopMenu.vue')['default']
    README: typeof import('./components/README.md')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    UserDesc: typeof import('./components/UserDesc.vue')['default']
  }
}
